export default {
  SEARCH_API_URL        :   'http://gateway-dev.fptechscience.com/search',
  CATALOG_API_URL       :   'http://catalogapis-dev.fptechscience.com',
  LISTING_API_URL       :   'http://gateway-dev.fptechscience.com/listing',
  PIM_API_URL           :   'http://pimapis-dev.fptechscience.com/pim',
  CMS_API_URL           :   'http://gateway-dev.fptechscience.com/cms',
  ORDERS_API_URL        :   'http://gateway-dev.fptechscience.com/order',
  TRANSACTIONS_API_URL  :   'http://gateway-dev.fptechscience.com/transactions',
  AUTH_API_URL          :   'http://gateway-dev.fptechscience.com/auth-service',
  CART_API_URL          :   'http://gateway-dev.fptechscience.com/cart',
  CATEGORYTREE_API_URL  :   'http://gateway-dev.fptechscience.com/category-tree',
  WISHLIST_API_URL      :   'http://gateway-dev.fptechscience.com/wl',
  FCM_API_URL           :   'http://gateway-dev.fptechscience.com/fcm',
  VAULT_API_URL         :   'http://gateway-dev.fptechscience.com/vault',
};