const getConfig = require('next/config');

const config = getConfig.default();

let env = config || '';
env = env.publicRuntimeConfig || '';
env = env.env || '';

env = env || process.env.ENV;
env = env.trim();

const a = {
  local: {
    IMAGE_SEARCH_URL: 'http://192.168.0.180:9090/image-search',
    SEARCH_API_URL: 'http://192.168.0.180:9090/search',
    CATALOG_API_URL: 'http://http://apigatewayinternal-stage.fptsinternal.com/catalogapi',
    LISTING_API_URL: 'http://192.168.0.180:9090/listing',
    PIM_API_URL: 'http://http://apigatewayinternal-stage.fptsinternal.com/pim-service/pim',
    CMS_API_URL: 'http://192.168.0.180:9090/cms',
    ORDERS_API_URL: 'http://192.168.0.180:9090/order',
    TRANSACTIONS_API_URL: 'http://192.168.0.180:9090/transactions',
    AUTH_API_URL: 'http://192.168.0.180:9090/auth-service',
    CART_API_URL: 'http://192.168.0.180:9090/cart',
    CATEGORYTREE_API_URL: 'http://192.168.0.180:9090/category-tree',
    WISHLIST_API_URL: 'http://192.168.0.180:9090/wl',
    FCM_API_URL: 'http://192.168.0.180:9090/fcm',
    REVIEWS_API_URL: 'http://192.168.0.180:9090/reviews',
    VAULT_API_URL: 'http://192.168.0.180:9090/cms',
    TRANSFORMER_API_URL: 'https://apigateway-stage.tila.com/transformers',
    SUGGESSIONS_URL: 'http://192.168.0.180:9090/auto-suggest/suggest/suggestions',
    COUPONS_URL: 'http://192.168.0.180:9090/dip/fpts',
    CAPTCHA_URL: 'https://apigateway-stage.tila.com/transformers/api/v1/captcha',
    HNS_URL: 'https://apigateway-stage.tila.com/hns/api/v1',
    PCM_URL: 'https://apigateway-stage.tila.com/pcm/api/v1'
  },
  dev: {
    IMAGE_SEARCH_URL: 'https://apigateway-stage.tila.com/image-search',
    SEARCH_API_URL: 'https://apigateway-stage.tila.com/search',
    CATALOG_API_URL: 'http://http://apigatewayinternal-stage.fptsinternal.com/catalogapi',
    LISTING_API_URL: 'https://apigateway-stage.tila.com/listing',
    PIM_API_URL: 'http://http://apigatewayinternal-stage.fptsinternal.com/pim-service/pim',
    CMS_API_URL: 'https://apigateway-stage.tila.com/cms',
    ORDERS_API_URL: 'https://apigateway-stage.tila.com/order',
    REFUND_OPTIONS_URL:'https://apigateway-stage.tila.com/order_item',
    TRANSACTIONS_API_URL: 'https://apigateway-stage.tila.com/transactions',
    AUTH_API_URL: 'https://apigateway-stage.tila.com/auth-service',
    CART_API_URL: 'https://apigateway-stage.tila.com/cart',
    CATEGORYTREE_API_URL: 'https://apigateway-stage.tila.com/category-tree',
    WISHLIST_API_URL: 'https://apigateway-stage.tila.com/wl',
    FCM_API_URL: 'https://apigateway-stage.tila.com/fcm',
    REVIEWS_API_URL: 'https://apigateway-stage.tila.com/reviews',
    VAULT_API_URL: 'https://apigateway-stage.tila.com/cms',
    TRANSFORMER_API_URL: 'https://apigateway-stage.tila.com/transformers',
    SUGGESSIONS_URL: 'https://apigateway-stage.tila.com/auto-suggest/suggest/suggestions',
    COUPONS_URL: 'https://apigateway-stage.tila.com/dip/fpts',
    CAPTCHA_URL: 'https://apigateway-stage.tila.com/transformers/api/v1/captcha',
    HNS_URL: 'https://apigateway-stage.tila.com/hns/api/v1',
    LOGISTICS_URL: 'https://apigateway-stage.tila.com/logistics',
    PCM_URL: 'https://apigateway-stage.tila.com/pcm/api/v1'
    // IMAGE_SEARCH_URL: 'https://apigateway-dev.tila.com/image-search',
    // SEARCH_API_URL: 'https://apigateway-dev.tila.com/search',
    // CATALOG_API_URL: 'https://catalogapis-dev.fptechscience.com',
    // LISTING_API_URL: 'https://apigateway-dev.tila.com/listing',
    // PIM_API_URL: 'https://pimapis-dev.fptechscience.com/pim',
    // CMS_API_URL: 'https://apigateway-dev.tila.com/cms',
    // ORDERS_API_URL: 'https://apigateway-dev.tila.com/order',
    // REFUND_OPTIONS_URL:'https://apigateway-dev.tila.com/order_item',
    // TRANSACTIONS_API_URL: 'https://apigateway-dev.tila.com/transactions',
    // AUTH_API_URL: 'https://apigateway-dev.tila.com/auth-service',
    // CART_API_URL: 'https://apigateway-dev.tila.com/cart',
    // CATEGORYTREE_API_URL: 'https://apigateway-dev.tila.com/category-tree',
    // WISHLIST_API_URL: 'https://apigateway-dev.tila.com/wl',
    // FCM_API_URL: 'https://apigateway-dev.tila.com/fcm',
    // REVIEWS_API_URL: 'https://apigateway-dev.tila.com/reviews',
    // VAULT_API_URL: 'https://apigateway-dev.tila.com/cms',
    // TRANSFORMER_API_URL: 'https://apigateway-stage.tila.com/transformers',
    // SUGGESSIONS_URL: 'https://apigateway-stage.tila.com/auto-suggest/suggest/suggestions',
    // COUPONS_URL: 'https://apigateway-stage.tila.com/dip/fpts',
    // CAPTCHA_URL: 'https://apigateway-stage.tila.com/transformers/api/v1/captcha',
    // HNS_URL: 'https://apigateway-dev.tila.com/hns/api/v1',
  },
  staging: {
    IMAGE_SEARCH_URL: 'https://apigateway-stage.tila.com/image-search',
    SEARCH_API_URL: 'https://apigateway-stage.tila.com/search',
    CATALOG_API_URL: 'http://http://apigatewayinternal-stage.fptsinternal.com/catalogapi',
    LISTING_API_URL: 'https://apigateway-stage.tila.com/listing',
    PIM_API_URL: 'http://http://apigatewayinternal-stage.fptsinternal.com/pim-service/pim',
    CMS_API_URL: 'https://apigateway-stage.tila.com/cms',
    ORDERS_API_URL: 'https://apigateway-stage.tila.com/order',
    REFUND_OPTIONS_URL:'https://apigateway-stage.tila.com/order_item',
    TRANSACTIONS_API_URL: 'https://apigateway-stage.tila.com/transactions',
    AUTH_API_URL: 'https://apigateway-stage.tila.com/auth-service',
    CART_API_URL: 'https://apigateway-stage.tila.com/cart',
    CATEGORYTREE_API_URL: 'https://apigateway-stage.tila.com/category-tree',
    WISHLIST_API_URL: 'https://apigateway-stage.tila.com/wl',
    FCM_API_URL: 'https://apigateway-stage.tila.com/fcm',
    REVIEWS_API_URL: 'https://apigateway-stage.tila.com/reviews',
    VAULT_API_URL: 'https://apigateway-stage.tila.com/cms',
    TRANSFORMER_API_URL: 'https://apigateway-stage.tila.com/transformers',
    SUGGESSIONS_URL: 'https://apigateway-stage.tila.com/auto-suggest/suggest/suggestions',
    COUPONS_URL: 'https://apigateway-stage.tila.com/dip/fpts',
    CAPTCHA_URL: 'https://apigateway-stage.tila.com/transformers/api/v1/captcha',
    HNS_URL: 'https://apigateway-stage.tila.com/hns/api/v1',
    LOGISTICS_URL: 'https://apigateway-stage.tila.com/logistics',
    PCM_URL: 'https://apigateway-stage.tila.com/pcm/api/v1'
  },
  stage: {
    IMAGE_SEARCH_URL: 'https://apigateway-stage.tila.com/image-search',
    SEARCH_API_URL: 'https://apigateway-stage.tila.com/search',
    CATALOG_API_URL: 'http://http://apigatewayinternal-stage.fptsinternal.com/catalogapi',
    LISTING_API_URL: 'https://apigateway-stage.tila.com/listing',
    PIM_API_URL: 'http://http://apigatewayinternal-stage.fptsinternal.com/pim-service/pim',
    CMS_API_URL: 'https://apigateway-stage.tila.com/cms',
    ORDERS_API_URL: 'https://apigateway-stage.tila.com/order',
    REFUND_OPTIONS_URL:'https://apigateway-stage.tila.com/order_item',
    TRANSACTIONS_API_URL: 'https://apigateway-stage.tila.com/transactions',
    AUTH_API_URL: 'https://apigateway-stage.tila.com/auth-service',
    CART_API_URL: 'https://apigateway-stage.tila.com/cart',
    CATEGORYTREE_API_URL: 'https://apigateway-stage.tila.com/category-tree',
    WISHLIST_API_URL: 'https://apigateway-stage.tila.com/wl',
    FCM_API_URL: 'https://apigateway-stage.tila.com/fcm',
    REVIEWS_API_URL: 'https://apigateway-stage.tila.com/reviews',
    VAULT_API_URL: 'https://apigateway-stage.tila.com/cms',
    TRANSFORMER_API_URL: 'https://apigateway-stage.tila.com/transformers',
    SUGGESSIONS_URL: 'https://apigateway-stage.tila.com/auto-suggest/suggest/suggestions',
    COUPONS_URL: 'https://apigateway-stage.tila.com/dip/fpts',
    CAPTCHA_URL: 'https://apigateway-stage.tila.com/transformers/api/v1/captcha',
    HNS_URL: 'https://apigateway-stage.tila.com/hns/api/v1',
    LOGISTICS_URL: 'https://apigateway-stage.tila.com/logistics',
    PCM_URL: 'https://apigateway-stage.tila.com/pcm/api/v1'
  },
  preprod: {
    IMAGE_SEARCH_URL: 'https://apigateway-preprod.tila.com/image-search',
    SEARCH_API_URL: 'https://apigateway-preprod.tila.com/search',
    CATALOG_API_URL: 'http://http://apigatewayinternal-stage.fptsinternal.com/catalogapi',
    LISTING_API_URL: 'https://apigateway-preprod.tila.com/listing',
    PIM_API_URL: 'http://apigatewayinternal-preprod.fptsinternal.com/pim-service/pim',
    CMS_API_URL: 'https://apigateway-preprod.tila.com/cms',
    ORDERS_API_URL: 'https://apigateway-preprod.tila.com/order',
    REFUND_OPTIONS_URL:'https://apigateway-preprod.tila.com/order_item',
    TRANSACTIONS_API_URL: 'https://apigateway-preprod.tila.com/transactions',
    AUTH_API_URL: 'https://apigateway-preprod.tila.com/auth-service',
    CART_API_URL: 'https://apigateway-preprod.tila.com/cart',
    CATEGORYTREE_API_URL: 'https://apigateway-preprod.tila.com/category-tree',
    WISHLIST_API_URL: 'https://apigateway-preprod.tila.com/wl',
    FCM_API_URL: 'https://apigateway-preprod.tila.com/fcm',
    REVIEWS_API_URL: 'https://apigateway-preprod.tila.com/reviews',
    VAULT_API_URL: 'https://apigateway-preprod.tila.com/cms',
    HNS_URL: 'https://apigateway-preprod.tila.com/hns/api/v1',
    TRANSFORMER_API_URL: 'https://apigateway-preprod.tila.com/transformers',
    SUGGESSIONS_URL: 'https://apigateway-preprod.tila.com/auto-suggest/suggest/suggestions',
    COUPONS_URL: 'https://apigateway-preprod.tila.com/dip/fpts',
    CAPTCHA_URL: 'https://apigateway-preprod.tila.com/transformers/api/v1/captcha',
    LOGISTICS_URL: 'https://apigateway-preprod.tila.com/logistics',
    PCM_URL: 'https://apigateway-preprod.tila.com/pcm/api/v1'
  },
  prod: {
    IMAGE_SEARCH_URL: 'https://apigateway.tila.com/image-search',
    SEARCH_API_URL: 'https://search-api.tila.com',
    CATALOG_API_URL: 'http://http://apigatewayinternal-stage.fptsinternal.com/catalogapi',
    LISTING_API_URL: 'https://apigateway.tila.com/listing',
    PIM_API_URL: 'http://apigatewayinternal-preprod.fptsinternal.com/pim-service/pim',
    CMS_API_URL: 'https://apigateway.tila.com/cms',
    ORDERS_API_URL: 'https://apigateway.tila.com/order',
    REFUND_OPTIONS_URL:'https://apigateway.tila.com/order_item',
    TRANSACTIONS_API_URL: 'https://apigateway.tila.com/transactions',
    AUTH_API_URL: 'https://apigateway.tila.com/auth-service',
    CART_API_URL: 'https://apigateway.tila.com/cart',
    CATEGORYTREE_API_URL: 'https://apigateway.tila.com/category-tree',
    WISHLIST_API_URL: 'https://apigateway.tila.com/wl',
    FCM_API_URL: 'https://apigateway.tila.com/fcm',
    REVIEWS_API_URL: 'https://apigateway.tila.com/reviews',
    VAULT_API_URL: 'https://apigateway.tila.com/cms',
    HNS_URL: 'https://apigateway.tila.com/hns/api/v1',
    TRANSFORMER_API_URL: 'https://apigateway.tila.com/transformers',
    SUGGESSIONS_URL: 'https://apigateway.tila.com/auto-suggest/suggest/suggestions',
    COUPONS_URL: 'https://apigateway.tila.com/dip/fpts',
    CAPTCHA_URL: 'https://apigateway.tila.com/transformers/api/v1/captcha',
    LOGISTICS_URL: 'https://apigateway.tila.com/logistics',
    PCM_URL: 'https://apigateway.tila.com/pcm/api/v1'
  },
  production: {
    IMAGE_SEARCH_URL: 'https://apigateway.tila.com/image-search',
    SEARCH_API_URL: 'https://search-api.tila.com',
    CATALOG_API_URL: 'http://http://apigatewayinternal-stage.fptsinternal.com/catalogapi',
    LISTING_API_URL: 'https://apigateway.tila.com/listing',
    PIM_API_URL: 'http://apigatewayinternal-preprod.fptsinternal.com/pim-service/pim',
    CMS_API_URL: 'https://apigateway.tila.com/cms',
    ORDERS_API_URL: 'https://apigateway.tila.com/order',
    REFUND_OPTIONS_URL:'https://apigateway.tila.com/order_item',
    TRANSACTIONS_API_URL: 'https://apigateway.tila.com/transactions',
    AUTH_API_URL: 'https://apigateway.tila.com/auth-service',
    CART_API_URL: 'https://apigateway.tila.com/cart',
    CATEGORYTREE_API_URL: 'https://apigateway.tila.com/category-tree',
    WISHLIST_API_URL: 'https://apigateway.tila.com/wl',
    FCM_API_URL: 'https://apigateway.tila.com/fcm',
    REVIEWS_API_URL: 'https://apigateway.tila.com/reviews',
    VAULT_API_URL: 'https://apigateway.tila.com/cms',
    HNS_URL: 'https://apigateway.tila.com/hns/api/v1',
    TRANSFORMER_API_URL: 'https://apigateway.tila.com/transformers',
    SUGGESSIONS_URL: 'https://apigateway.tila.com/auto-suggest/suggest/suggestions',
    COUPONS_URL: 'https://apigateway.tila.com/dip/fpts',
    CAPTCHA_URL: 'https://apigateway.tila.com/transformers/api/v1/captcha',
    LOGISTICS_URL: 'https://apigateway.tila.com/logistics',
    PCM_URL: 'https://apigateway.tila.com/pcm/api/v1'
  }
};
// console.log('constants.js 2', a);
const b = env || 'preprod';
const c = a[b];

module.exports = c;
